## Muhamad Fadhli Akbar(Cortana)

### Assignment Machine Learning 01 About Scikit Learn Introduction

If **file code & images** cannot be accessed, you can use the repository link which can be accessed by using [this link!](https://github.com/Cortana-Coders/AICI-Tasks/blob/main/Assigment-Machine-Learning/Muhamad%20Fadhli%20Akbar-Cortana-ML%2001.ipynb "link github")

In [3]:
import numpy as np
from sklearn import preprocessing

# Generate random input data
input_data = np.random.uniform(-6.0, 6.0, size=(4, 3))
print("Input Data:\n", input_data)

Input Data:
 [[ 4.53773631 -2.29331051  3.8730088 ]
 [-2.63873697 -2.74483428  5.45842035]
 [-1.70117843 -5.72231564 -2.39979473]
 [-3.36804065  2.5803456   3.14397236]]


In [2]:
from sklearn.preprocessing import Binarizer

# Apply binarization with threshold 0.7
binarizer = Binarizer(threshold=0.7)
data_binarized = binarizer.fit_transform(input_data)

print("Binarized data:\n", data_binarized)

Binarized data:
 [[1. 1. 0.]
 [1. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [5]:
# Perform scaling with both normalization methods on input_data

from sklearn.preprocessing import MinMaxScaler, MaxAbsScaler, StandardScaler

# Apply Min-Max scaling
min_max_scaler = MinMaxScaler()
scaled_data1 = min_max_scaler.fit_transform(input_data)
print("Min Max scaled data:\n", scaled_data1, '\n')

# Apply Max-Abs scaling
max_abs_scaler = MaxAbsScaler()
scaled_data2 = max_abs_scaler.fit_transform(input_data)
print("Max Abs scaled data:\n", scaled_data2, '\n')

Min Max scaled data:
 [[1.         0.41300073 0.79824788]
 [0.09224946 0.35861771 1.        ]
 [0.21084104 0.         0.        ]
 [0.         1.         0.70547408]] 

Max Abs scaled data:
 [[ 1.         -0.40076617  0.70954755]
 [-0.58150954 -0.47967195  1.        ]
 [-0.37489583 -1.         -0.43965004]
 [-0.74222926  0.45092682  0.57598575]] 



In [6]:
# Scalling with method standardization

std_scaler = StandardScaler()
std_data = std_scaler.fit_transform(input_data)
print("Standardized data: \n", std_data)

Standardized data: 
 [[ 1.70098342 -0.08337909  0.4573886 ]
 [-0.58914699 -0.2350118   0.99290692]
 [-0.28995667 -1.23492274 -1.6614311 ]
 [-0.82187976  1.55331362  0.21113558]]


In [3]:
import pandas as pd

df = pd.DataFrame({
    'name': ['J.A.R.V.I.S', 'WALL-E', 'Baymax', 'BB-8', 'Cortana'],
    'color': ['blue', 'brown', 'white', 'yellow', 'blue'],
    'type': ['live', 'cartoon', 'cartoon', 'live', 'cartoon' ]
    })
df

name   color     type
0  J.A.R.V.I.S    blue     live
1       WALL-E   brown  cartoon
2       Baymax   white  cartoon
3         BB-8  yellow     live
4      Cortana    blue  cartoon

In [13]:
import pandas as pd
from sklearn import preprocessing

df['encoded_color'] = preprocessing.LabelEncoder().fit_transform(df['color'])
df

name   color     type  encoded_color  cartoon  live  cartoon  live
0  J.A.R.V.I.S    blue     live              0      0.0   1.0      0.0   1.0
1       WALL-E   brown  cartoon              1      1.0   0.0      1.0   0.0
2       Baymax   white  cartoon              2      1.0   0.0      1.0   0.0
3         BB-8  yellow     live              3      0.0   1.0      0.0   1.0
4      Cortana    blue  cartoon              0      1.0   0.0      1.0   0.0

In [14]:
from sklearn.preprocessing import OneHotEncoder

color_colums = []
for col in df['color'].unique():
    color_colums.append(col)

onehot_encoded_color = preprocessing.OneHotEncoder().fit_transform(df[['color']])
df2 = pd.DataFrame(onehot_encoded_color.toarray(), columns=color_colums)
pd.concat([df, df2], axis=1)

name   color     type  encoded_color  cartoon  live  cartoon  live  \
0  J.A.R.V.I.S    blue     live              0      0.0   1.0      0.0   1.0   
1       WALL-E   brown  cartoon              1      1.0   0.0      1.0   0.0   
2       Baymax   white  cartoon              2      1.0   0.0      1.0   0.0   
3         BB-8  yellow     live              3      0.0   1.0      0.0   1.0   
4      Cortana    blue  cartoon              0      1.0   0.0      1.0   0.0   

   blue  brown  white  yellow  
0   1.0    0.0    0.0     0.0  
1   0.0    1.0    0.0     0.0  
2   0.0    0.0    1.0     0.0  
3   0.0    0.0    0.0     1.0  
4   1.0    0.0    0.0     0.0

In [4]:
# loading iris dataset

from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target
feature_names = iris.feature_names
target_names = iris.target_names

print("Feature names:", feature_names)
print("Target names:", target_names)
print("First 10 rows of X:\n", X[:10])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']
First 10 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [20]:
# Splitting dataset

from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

iris = load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.3, random_state = 1
)

print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(105, 4)
(45, 4)
(105,)
(45,)


In [21]:
# Train the model using the KNN algorithm (or you can try other algorithms) with free neighbor parameters.
# also show the accuracy of the resulting model

from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
classifier_knn = KNeighborsClassifier(n_neighbors=3)
classifier_knn.fit(X_train, y_train)
y_pred = classifier_knn.predict(X_test)

# finding accuracy by comparing actual response values
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

sample = [[5, 5, 3, 2], [2, 4, 3, 5]]
preds = classifier_knn.predict(sample)
pred_species = [iris.target_names[p] for p in preds] 
print("Predictions:", pred_species)


Accuracy: 0.9777777777777777
Predictions: ['versicolor', 'virginica']


In [22]:
# save the model with joblib

import joblib
joblib.dump(classifier_knn, 'iris_classifier_knn.joblib')

['iris_classifier_knn.joblib']

In [23]:
# Load the previously saved model

joblib.load('iris_classifier_knn.joblib')

KNeighborsClassifier(n_neighbors=3)

## **THANK YOU**

<img src="https://i.pinimg.com/originals/7c/b0/f6/7cb0f6a884078a4bacf5b42b8bd6eb16.gif" width=80%>