## Muhamad Fadhli Akbar(Cortana)

### Assignment EDA 3 & 4

Jika **file code & gambar** tidak bisa diakses, bisa menggunakan link repository yang bisa diakses dengan menggunakan [link ini](https://github.com/Cortana-Coders/AICI-Tasks/blob/main/Assigment-Data-Analysis/Muhamad%20Fadhli%20Akbar-Cortana-EDA%203%20dan%204.ipynb "link github")

In [3]:
import numpy as np
from sklearn import preprocessing

# Generate random input data
input_data = np.random.uniform(-6.0, 6.0, size=(4, 3))
print("Input Data:\n", input_data)

Input Data:
 [[ 4.53773631 -2.29331051  3.8730088 ]
 [-2.63873697 -2.74483428  5.45842035]
 [-1.70117843 -5.72231564 -2.39979473]
 [-3.36804065  2.5803456   3.14397236]]


In [2]:
# Lakukanlah binarization terhadap input_data dengan threshold 0.7
from sklearn.preprocessing import Binarizer

# Apply binarization with threshold 0.7
binarizer = Binarizer(threshold=0.7)
data_binarized = binarizer.fit_transform(input_data)

print("Binarized data:\n", data_binarized)

Binarized data:
 [[1. 1. 0.]
 [1. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [5]:
# Lakukanlah scalling dengan kedua metode normalization terhadap input_data

from sklearn.preprocessing import MinMaxScaler, MaxAbsScaler, StandardScaler

# Apply Min-Max scaling
min_max_scaler = MinMaxScaler()
scaled_data1 = min_max_scaler.fit_transform(input_data)
print("Min Max scaled data:\n", scaled_data1, '\n')

# Apply Max-Abs scaling
max_abs_scaler = MaxAbsScaler()
scaled_data2 = max_abs_scaler.fit_transform(input_data)
print("Max Abs scaled data:\n", scaled_data2, '\n')

Min Max scaled data:
 [[1.         0.41300073 0.79824788]
 [0.09224946 0.35861771 1.        ]
 [0.21084104 0.         0.        ]
 [0.         1.         0.70547408]] 

Max Abs scaled data:
 [[ 1.         -0.40076617  0.70954755]
 [-0.58150954 -0.47967195  1.        ]
 [-0.37489583 -1.         -0.43965004]
 [-0.74222926  0.45092682  0.57598575]] 



In [6]:
# Scalling with method standardization

std_scaler = StandardScaler()
std_data = std_scaler.fit_transform(input_data)
print("Standardized data: \n", std_data)

Standardized data: 
 [[ 1.70098342 -0.08337909  0.4573886 ]
 [-0.58914699 -0.2350118   0.99290692]
 [-0.28995667 -1.23492274 -1.6614311 ]
 [-0.82187976  1.55331362  0.21113558]]


In [7]:
import pandas as pd

df = pd.DataFrame({
    'name': ['J.A.R.V.I.S', 'WALL-E', 'Baymax', 'BB-8', 'Cortana'],
    'color': ['blue', 'brown', 'white', 'yellow', 'blue'],
    'type': ['live', 'cartoon', 'cartoon', 'live', 'cartoon' ]
    })
df

name   color     type
0  J.A.R.V.I.S    blue     live
1       WALL-E   brown  cartoon
2       Baymax   white  cartoon
3         BB-8  yellow     live
4      Cortana    blue  cartoon