In [12]:
import numpy as np
from sklearn import preprocessing
input_data = np.random.uniform(-6.0,6.0, size=(4,3))
print(input_data)

[[ 0.93024391  4.74829136 -3.98601296]
 [ 1.67733097 -4.0479681  -5.0392528 ]
 [ 5.89574252 -4.13315319  2.83207394]
 [ 1.26936533 -4.59370737  3.69693312]]


In [13]:
# Lakukanlah binarization terhadap input_data dengan threshold 0.7

data_binarized = ...
print("Binarized data:\n", data_binarized)

Binarized data:
 [[1. 1. 0.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 0. 1.]]


In [ ]:
# Lakukanlah scalling dengan kedua metode normalization terhadap input_data

scaled_data1 = ...
print ("Min Max scaled data:\n", scaled_data1,'\n')

scaled_data2 = ...
print ("Max Abs scaled data:\n", scaled_data2,'\n')

Min Max scaled data:
 [[0.48648649 0.58252427 0.99122807]
 [0.         1.         0.81578947]
 [0.27027027 0.         1.        ]
 [1.         0.99029126 0.        ]] 

Max Abs scaled data:
 [[ 0.3559322  -0.24050633  0.94827586]
 [-0.25423729  0.30379747  0.60344828]
 [ 0.08474576 -1.          0.96551724]
 [ 1.          0.29113924 -1.        ]] 



In [ ]:
# Lakukanlah scaling dengan metode standardization terhadap input_data

std_data = ...
print ("Normalized data:\n", std_data)

Normalized data:
 [[ 0.12894603 -0.14880162  0.70300338]
 [-1.19735598  0.8749535   0.27694073]
 [-0.46052153 -1.57729713  0.72430651]
 [ 1.52893149  0.85114524 -1.70425062]]


In [2]:
import pandas as pd

df = pd.DataFrame({
    'name': ['J.A.R.V.I.S', 'WALL-E', 'Baymax', 'BB-8', 'Cortana'],
    'color': ['blue', 'brown', 'white', 'yellow', 'blue'],
    'type': ['live', 'cartoon', 'cartoon', 'live', 'cartoon' ]
    })
df

name   color     type
0  J.A.R.V.I.S    blue     live
1       WALL-E   brown  cartoon
2       Baymax   white  cartoon
3         BB-8  yellow     live
4      Cortana    blue  cartoon

In [ ]:
# Lakukanlah label encoding terhadap kolom type

df['...'] = ...
df

name   color  encoded_color
0  J.A.R.V.I.S    blue              0
1       WALL-E   brown              1
2       Baymax   white              2
3         BB-8  yellow              3
4      Cortana    blue              0

In [ ]:
# Lakukanlah one-hot encoding terhadap kolom type

type_columns = []
for t in df['type'].unique():
  type_columns.append(t)

onehot_encoded_type = ....
df2 = pd.DataFrame(onehot_encoded_type.toarray(), columns=type_columns)
pd.concat([df, df2], axis=1)

name   color  encoded_color  blue  brown  white  yellow
0  J.A.R.V.I.S    blue              0   1.0    0.0    0.0     0.0
1       WALL-E   brown              1   0.0    1.0    0.0     0.0
2       Baymax   white              2   0.0    0.0    1.0     0.0
3         BB-8  yellow              3   0.0    0.0    0.0     1.0
4      Cortana    blue              0   1.0    0.0    0.0     0.0

In [ ]:
# Lakukanlah loading dataset iris

from sklearn.datasets import ...
iris = ...
X = ...
y = ...
feature_names = ...
target_names = ...
print("Feature names:", feature_names)
print("Target names:", target_names)
print("First 10 rows of X:\n", X[:10])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']
First 10 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [ ]:
# Lakukanlah splitting dataset

from sklearn.model_selection import ...

..., ..., ..., ... = ...

print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(105, 4)
(45, 4)
(105,)
(45,)


In [ ]:
# Lakukanlah training model menggunakan algoritma KNN ( atau boleh juga mencoba dengan algoritma lain) dengan parameter neighbor bebas
# tampilkan juga akurasi dari model yang dihasilkan

...
...
classifier = ...
...
...

# Finding accuracy by comparing actual response values(y_test)with predicted response value(y_pred)
print("Accuracy:", ...)

# Providing sample data and the model will make prediction out of that data
sample = [[5, 5, 3, 2], [2, 4, 3, 5]]
preds = classifier.predict(sample)
pred_species = [iris.target_names[p] for p in preds] 
print("Predictions:", pred_species)

Accuracy: 0.9777777777777777
Predictions: ['versicolor', 'virginica']


In [ ]:
# Simpanlah model yang telah di training sebelumnya menggunakan joblib

import ...
...

['iris_classifier_knn.joblib']

In [ ]:
# Load model yang telah di save sebelumnya

...

KNeighborsClassifier(n_neighbors=3)