## Exploratory Data Analysis
### Assigment 2 About Numpy

**Muhamad Fadhli Akbar-Cortana**

1. Buatlah program Numpy dimana didapatkan vektor dengan panjang 10 dan angkanya enyebar merata antara 5 sampai 50 

In [2]:
import numpy as np

vektor = np.random.uniform(5, 50, 10)
print(vektor)

[47.53109684 29.79757508  9.17992343 30.87626876 45.1714927  20.82067406
 22.84457822 45.89761436 49.18299755 39.53583152]


2. Buatlah matriks identitas 3x3 dimana nilai diagonal = 1, sisanya 0 

In [2]:
import numpy as np
matrix_identitas = np.eye(3)
print(matrix_identitas)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



3. Hitunglah rata rata, variansi dan standar deviasi dari x = np.random.randint(10,31, size = (1,5))

In [3]:
import numpy as np

x = np.random.randint(10, 31, size=(1, 5))

rata_rata = np.mean(x)
variansi = np.var(x)
standar_deviasi = np.std(x)

print("Rata-rata: ", rata_rata)
print("Variansi: ", variansi)
print("Standar Deviasi: ", standar_deviasi)

Rata-rata:  25.4
Variansi:  10.24
Standar Deviasi:  3.2


4.  Hitunglah  nilai  rata  rata  dari  2  array  numpy  dimana  arr1  =  np.array([3,4])  dan  arr2  = np.array([1,0]) 

In [4]:
array_1 = np.array([3, 4])
array_2 = np.array([1, 0])

rata_rata_elemen = (array_1 + array_2) / 2
print("Rata-rata setiap elemen:", rata_rata_elemen)

rata_rata_keseluruhan = np.mean(np.concatenate((array_1, array_2)))
print("Rata-rata keseluruhan:", rata_rata_keseluruhan)

Rata-rata setiap elemen: [2. 2.]
Rata-rata keseluruhan: 2.0


5. Hitunglah akar pada vektor yang dihasilkan dari pertanyaan **nomor 1**

In [6]:
import numpy as np

# Vektor soal pertama
vektor = np.random.uniform(5, 50, 10)

akar_vektor = np.sqrt(vektor)
print("Akar Vektor: ", akar_vektor)

NameError: name 'vektor' is not defined